import type { TEventColor } from './types';
import type { IEvent, IEventLocation, IUser } from './interfaces';

// ================================== //

export const USERS_MOCK: IUser[] = [
	{
		id: 'b1f6d2c4-8a3e-4f21-9c7b-2d5e6f8a1b30',
		name: 'Rohit',
		picturePath: 'https://www.rohitk06.in/android-chrome-512x512.png'
	},
	{
		id: 'dd503cf9-6c38-43cf-94cc-0d4032e2f77a',
		name: 'Leonardo Ramos',
		// Deterministic placeholder avatars, seeded by id so each user is stable.
		picturePath: 'https://i.pravatar.cc/150?u=dd503cf9-6c38-43cf-94cc-0d4032e2f77a'
	},
	{
		id: 'f3b035ac-49f7-4e92-a715-35680bf63175',
		name: 'Michael Doe',
		picturePath: 'https://i.pravatar.cc/150?u=f3b035ac-49f7-4e92-a715-35680bf63175'
	},
	{
		id: '3e36ea6e-78f3-40dd-ab8c-a6c737c3c422',
		name: 'Alice Johnson',
		picturePath: 'https://i.pravatar.cc/150?u=3e36ea6e-78f3-40dd-ab8c-a6c737c3c422'
	},
	{
		id: 'a7aff6bd-a50a-4d6a-ab57-76f76bb27cf5',
		name: 'Robert Smith',
		picturePath: 'https://i.pravatar.cc/150?u=a7aff6bd-a50a-4d6a-ab57-76f76bb27cf5'
	}
];

const COLORS: TEventColor[] = ['blue', 'green', 'red', 'yellow', 'purple', 'orange', 'gray'];

// Sample locations: a mix of online meetings (real provider hosts, so the
// favicon/label derivation has something to work with) and physical addresses
// (well-known places so the map geocodes reliably).
const LOCATIONS: IEventLocation[] = [
	{ type: 'online', url: 'https://zoom.us/j/9876543210' },
	{ type: 'online', url: 'https://meet.google.com/abc-defg-hij' },
	{ type: 'online', url: 'https://teams.microsoft.com/l/meetup-join/19:meeting_xyz' },
	{ type: 'online', url: 'https://meet.jit.si/big-calendar-sync' },
	{ type: 'physical', address: '350 5th Ave, New York, NY 10118, USA' },
	{ type: 'physical', address: '1600 Amphitheatre Parkway, Mountain View, CA 94043, USA' },
	{ type: 'physical', address: '10 Downing St, London SW1A 2AA, UK' },
	{ type: 'physical', address: 'Praça da Sé, São Paulo, Brazil' }
];

const EVENTS = [
	"Doctor's appointment",
	'Dental cleaning',
	'Eye exam',
	'Therapy session',
	'Business meeting',
	'Team stand-up',
	'Project deadline',
	'Weekly report submission',
	'Client presentation',
	'Marketing strategy review',
	'Networking event',
	'Sales call',
	'Investor pitch',
	'Board meeting',
	'Employee training',
	'Performance review',
	'One-on-one meeting',
	'Lunch with a colleague',
	'HR interview',
	'Conference call',
	'Web development sprint planning',
	'Software deployment',
	'Code review',
	'QA testing session',
	'Cybersecurity audit',
	'Server maintenance',
	'API integration update',
	'Data backup',
	'Cloud migration',
	'System upgrade',
	'Content planning session',
	'Product launch',
	'Customer support review',
	'Team building activity',
	'Legal consultation',
	'Budget review',
	'Financial planning session',
	'Tax filing deadline',
	'Investor relations update',
	'Partnership negotiation',
	'Medical check-up',
	'Vaccination appointment',
	'Blood donation',
	'Gym workout',
	'Yoga class',
	'Physical therapy session',
	'Nutrition consultation',
	'Personal trainer session',
	'Parent-teacher meeting',
	'School open house',
	'College application deadline',
	'Final exam',
	'Graduation ceremony',
	'Job interview',
	'Internship orientation',
	'Office relocation',
	'Business trip',
	'Flight departure',
	'Hotel check-in',
	'Vacation planning',
	'Birthday party',
	'Wedding anniversary',
	'Family reunion',
	'Housewarming party',
	'Community volunteer work',
	'Charity fundraiser',
	'Religious service',
	'Concert attendance',
	'Theater play',
	'Movie night',
	'Sporting event',
	'Football match',
	'Basketball game',
	'Tennis practice',
	'Marathon training',
	'Cycling event',
	'Fishing trip',
	'Camping weekend',
	'Hiking expedition',
	'Photography session',
	'Art workshop',
	'Cooking class',
	'Book club meeting',
	'Grocery shopping',
	'Car maintenance',
	'Home renovation meeting'
];

// This was generated by AI -- minus the part where I added my wedding as an "easter egg" :)
const mockGenerator = (numberOfEvents: number): IEvent[] => {
	const result: IEvent[] = [
		{
			id: 1204,
			startDate: new Date('2025-09-20T00:00:00-03:00').toISOString(),
			endDate: new Date('2025-09-20T23:59:00-03:00').toISOString(),
			title: 'My wedding :)',
			color: 'red',
			description: "Can't wait to see the most beautiful woman in that dress!",
			// The original author's easter egg — keep it pinned to Leonardo even as
			// other users are added ahead of him in the list.
			user: USERS_MOCK.find((u) => u.name === 'Leonardo Ramos') ?? USERS_MOCK[0],
			location: { type: 'physical', address: 'Copacabana Beach, Rio de Janeiro, Brazil' }
		}
	];

	let currentId = 1;

	const randomUser = USERS_MOCK[Math.floor(Math.random() * USERS_MOCK.length)];

	// Date range: 30 days before and after now
	const now = new Date();
	const startRange = new Date(now);
	startRange.setDate(now.getDate() - 30);
	const endRange = new Date(now);
	endRange.setDate(now.getDate() + 30);

	// Create an event happening now
	const currentEvent = {
		id: currentId++,
		startDate: new Date(now.getTime() - 30 * 60000).toISOString(),
		endDate: new Date(now.getTime() + 30 * 60000).toISOString(),
		title: EVENTS[Math.floor(Math.random() * EVENTS.length)],
		color: COLORS[Math.floor(Math.random() * COLORS.length)],
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		user: randomUser
	};

	// Only add the current event if it's not on September 20th
	if (now.getMonth() !== 8 || now.getDate() !== 20) {
		// Month is 0-indexed (8 = September)
		result.push(currentEvent);
	}

	// A handful of events pinned to Rohit, spread across the next few days with a
	// mix of online links and physical locations, so his events (and the location
	// feature) are always visible without relying on the random assignment below.
	const rohit = USERS_MOCK.find((u) => u.name === 'Rohit') ?? USERS_MOCK[0];
	const rohitEvents: {
		dayOffset: number;
		hour: number;
		durationMin: number;
		title: string;
		color: TEventColor;
		location: IEventLocation;
	}[] = [
		{
			dayOffset: 0,
			hour: 15,
			durationMin: 45,
			title: 'Design sync',
			color: 'blue',
			location: { type: 'online', url: 'https://meet.google.com/rohit-design-sync' }
		},
		{
			dayOffset: 1,
			hour: 10,
			durationMin: 30,
			title: 'Sprint planning',
			color: 'purple',
			location: { type: 'online', url: 'https://zoom.us/j/rohit1234' }
		},
		{
			dayOffset: 1,
			hour: 13,
			durationMin: 60,
			title: 'Lunch with the team',
			color: 'orange',
			location: { type: 'physical', address: 'Cubbon Park, Bengaluru, India' }
		},
		{
			dayOffset: 2,
			hour: 11,
			durationMin: 45,
			title: '1:1 with manager',
			color: 'green',
			location: { type: 'online', url: 'https://teams.microsoft.com/l/meetup-join/rohit-1on1' }
		},
		{
			dayOffset: 3,
			hour: 18,
			durationMin: 90,
			title: 'Client workshop',
			color: 'red',
			location: { type: 'physical', address: 'WeWork Galaxy, Residency Road, Bengaluru, India' }
		}
	];

	for (const spec of rohitEvents) {
		const start = new Date(now);
		start.setDate(now.getDate() + spec.dayOffset);
		start.setHours(spec.hour, 0, 0, 0);
		const end = new Date(start.getTime() + spec.durationMin * 60 * 1000);

		result.push({
			id: currentId++,
			startDate: start.toISOString(),
			endDate: end.toISOString(),
			title: spec.title,
			color: spec.color,
			description:
				'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
			user: rohit,
			location: spec.location
		});
	}

	// Generate the remaining events
	let i = 0;
	let attempts = 0;
	const maxAttempts = numberOfEvents * 3; // Prevent infinite loop with a reasonable max attempts

	while (i < numberOfEvents - 1 && attempts < maxAttempts) {
		attempts++;

		// Determine if this is a multi-day event (10% chance)
		const isMultiDay = Math.random() < 0.1;

		const startDate = new Date(
			startRange.getTime() + Math.random() * (endRange.getTime() - startRange.getTime())
		);

		// Skip if the date is September 20th
		if (startDate.getMonth() === 8 && startDate.getDate() === 20) {
			continue;
		}

		// Set time between 8 AM and 8 PM
		startDate.setHours(8 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 4) * 15, 0, 0);

		const endDate = new Date(startDate);

		if (isMultiDay) {
			// Multi-day event: Add 1-4 days
			const additionalDays = Math.floor(Math.random() * 4) + 1;
			endDate.setDate(startDate.getDate() + additionalDays);

			// Ensure multi-day events don't cross September 20th
			const endMonth = endDate.getMonth();
			const endDay = endDate.getDate();
			const startMonth = startDate.getMonth();
			const startDay = startDate.getDate();

			// Check if event spans across September 20th
			if (
				(startMonth === 8 && startDay < 20 && (endMonth > 8 || (endMonth === 8 && endDay >= 20))) ||
				(endMonth === 8 && endDay >= 20 && (startMonth < 8 || (startMonth === 8 && startDay < 20)))
			) {
				continue;
			}

			endDate.setHours(
				8 + Math.floor(Math.random() * 12),
				Math.floor(Math.random() * 4) * 15,
				0,
				0
			);
		} else {
			const durationMinutes = (Math.floor(Math.random() * 11) + 2) * 15; // 30 to 180 minutes, multiple of 15
			endDate.setTime(endDate.getTime() + durationMinutes * 60 * 1000);
		}

		result.push({
			id: currentId++,
			startDate: startDate.toISOString(),
			endDate: endDate.toISOString(),
			title: EVENTS[Math.floor(Math.random() * EVENTS.length)],
			color: COLORS[Math.floor(Math.random() * COLORS.length)],
			description:
				'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
			user: USERS_MOCK[Math.floor(Math.random() * USERS_MOCK.length)],
			// Roughly a third of events carry a location, matching the React PR's mix.
			...(Math.random() < 0.3
				? { location: LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)] }
				: {})
		});

		i++;
	}

	return result;
};

export const CALENDAR_ITEMS_MOCK: IEvent[] = mockGenerator(80);
